import { mockProperties } from '../mock-data/properties';
import type { Property } from '../mock-data/types';
import { calculateMonthlyCost } from '../pricing';
import { calculateMatchScore, type SearchPreferences } from '../matching';
import { getStorageItem } from '../storage';
export type PropertyFilters=SearchPreferences&{type?:string;deposit?:string;brokerage?:boolean;amenities?:string[]};
export async function getProperties(filters:PropertyFilters={},sort='best'):Promise<Property[]>{const all=[...mockProperties,...getStorageItem<Property[]>('roomsaathi_owner_created',[])];let results=all.filter(p=>(filters.min==null||p.rent>=filters.min)&&(filters.max==null||p.rent<=filters.max)&&(filters.distance==null||p.commuteMinutes<=filters.distance)&&(!filters.accommodation||filters.accommodation==='Any'||p.accommodation.toLowerCase().includes(filters.accommodation.toLowerCase()))&&(!filters.destination||p.destination===filters.destination)&&(!filters.type||p.type===filters.type)&&(!filters.brokerage||p.brokerage===0)&&(!filters.deposit||filters.deposit==='any'||(filters.deposit==='0'?p.deposit===0:p.deposit<=Number(filters.deposit)))&&(!filters.food||filters.food==='any'||(filters.food==='included'?p.foodIncluded:filters.food==='available'?p.foodAvailable:!p.foodIncluded))&&(!filters.amenities?.length||filters.amenities.every(a=>p.amenities.some(x=>x.toLowerCase()===a.toLowerCase()))));
 const prefs:SearchPreferences=filters;
 if(sort==='cost')results.sort((a,b)=>calculateMonthlyCost(a)-calculateMonthlyCost(b)); else if(sort==='closest')results.sort((a,b)=>a.distanceKm-b.distanceKm); else if(sort==='movein')results.sort((a,b)=>(a.rent+a.deposit+a.brokerage)-(b.rent+b.deposit+b.brokerage)); else if(sort==='rating')results.sort((a,b)=>b.rating-a.rating); else if(sort==='newest')results.sort((a,b)=>Number.parseInt(a.updated)-Number.parseInt(b.updated)); else results.sort((a,b)=>calculateMatchScore(b,prefs)-calculateMatchScore(a,prefs)); return results; }
export async function getPropertyById(id:string){return [...mockProperties,...getStorageItem<Property[]>('roomsaathi_owner_created',[])].find(p=>p.id===id);}
export async function getAvailableBeds(id:string){const p=[...mockProperties,...getStorageItem<Property[]>('roomsaathi_owner_created',[])].find(x=>x.id===id);if(!p||p.availableBeds===0)return [];return Array.from({length:3},(_,i)=>({id:`${id}-bed-${i+1}`,room:'Room 201',bed:`Bed ${i+1}`,status:i<Math.min(p.availableBeds,2)?'Available':'Occupied'}));}
